### ISSUE TITLE
corregir texto en capitulo 1 

### ISSUE THREAD

**Issue by cbqmrec** [datosgcba/curso-datos#6]
Comunicación:
 (...)con un interlocutores(...)

quitar "un"

**Comment by cbqmrec** [comment]
en capitulo 2.1.2 también corregiría:
(...)profundiad_habitacion_m(...)
x2

por "profundidad".

**Comment by RacoFernandez** [comment]
Corregido! Muchas gracias por el aviso @cbqmrec
